name: sjmathew-site
region: sgp
static_sites:
  - name: web
    github:
      repo: rijosimon/sjmathew-site
      branch: main
      deploy_on_push: true
    environment_slug: node-js
    build_command: npm ci && npm run build
    output_dir: dist
    envs:
      - key: PUBLIC_MEDIA_BASE_URL
        value: https://sjmathew-media.sgp1.cdn.digitaloceanspaces.com
        scope: BUILD_TIME
    error_document: 404.html
